-- 1. Create 'pet' table
CREATE TABLE pet (
    pet_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_avatar VARCHAR(255),
    pet_name VARCHAR(255),
    pet_type VARCHAR(255),
    pet_age INT,
    pet_gender VARCHAR(255),
    slug VARCHAR(255) UNIQUE,
    create_at TIMESTAMP,
    update_at TIMESTAMP
);

-- 2. Create 'medicine' table
CREATE TABLE medicine (
    medicine_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_name VARCHAR(255),
    unit VARCHAR(255),
    description VARCHAR(255),
    create_at TIMESTAMP,
    update_at TIMESTAMP,
    create_by VARCHAR(255),
    update_by VARCHAR(255)
);

-- 3. Create 'medical_record' table
CREATE TABLE medical_record (
    medical_record_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP,
    diagnosis VARCHAR(255),
    treatment VARCHAR(255),
    create_at TIMESTAMP,
    update_at TIMESTAMP,
    create_by VARCHAR(255),
    update_by VARCHAR(255),
    pet_id INT,
    CONSTRAINT fk_medical_record_pet FOREIGN KEY (pet_id) REFERENCES pet(pet_id) ON DELETE CASCADE
);

-- 4. Create 'prescription' table
CREATE TABLE prescription (
    prescription_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quantity INT,
    create_at TIMESTAMP,
    update_at TIMESTAMP,
    create_by VARCHAR(255),
    update_by VARCHAR(255),
    medical_record_id INT,
    medicine_id INT,
    CONSTRAINT fk_prescription_medical_record FOREIGN KEY (medical_record_id) REFERENCES medical_record(medical_record_id) ON DELETE CASCADE,
    CONSTRAINT fk_prescription_medicine FOREIGN KEY (medicine_id) REFERENCES medicine(medicine_id) ON DELETE RESTRICT
);

-- 5. Create 'test_result' table
CREATE TABLE test_result (
    test_result_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    test_name VARCHAR(255),
    result VARCHAR(255),
    pdf_url VARCHAR(255),
    create_at TIMESTAMP,
    update_at TIMESTAMP,
    create_by VARCHAR(255),
    update_by VARCHAR(255),
    medical_record_id INT,
    CONSTRAINT fk_test_result_medical_record FOREIGN KEY (medical_record_id) REFERENCES medical_record(medical_record_id) ON DELETE CASCADE
);

-- 6. Create 'bill' table
CREATE TABLE bill (
    bill_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    total_price DOUBLE PRECISION,
    create_at TIMESTAMP,
    update_at TIMESTAMP,
    create_by VARCHAR(255),
    update_by VARCHAR(255),
    status VARCHAR(255),
    medical_record_id INT UNIQUE,
    CONSTRAINT fk_bill_medical_record FOREIGN KEY (medical_record_id) REFERENCES medical_record(medical_record_id) ON DELETE CASCADE
);
