spring.application.name=petcare
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/petcare_db}
spring.datasource.username=postgres
spring.datasource.password=ServBay.dev
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.jackson.time-zone=Asia/Ho_Chi_Minh
spring.jackson.serialization.write-dates-as-timestamps=false
spring.mvc.format.date-time=iso
vnpay.tmn-code=IC26HXN4
vnpay.hash-secret=C50GS36XIWTOBVUUF99D641XYKI23TZZ
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/payment-callback
